version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: marketplanet
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"

  app:
    build: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/marketplanet?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db